services:
  mi-mysql2:
    container_name: mi-mysql2
    networks:
      - mi-mysql-red2
    volumes:
      - mi-mysql-vol2:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    stdin_open: true 
    tty: true 
    image: mysql

  mi-dashboard2:
    container_name: mi-dashboard2
    networks:
      - mi-mysql-red2
    environment:
      - PMA_HOST=mi-mysql2
    ports:
      - 8080:80
    stdin_open: true 
    tty: true 
    image: phpmyadmin

networks:
  mi-mysql-red2:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
volumes:
  mi-mysql-vol2: